--[[-------------------------------------------------------------------------
Vehicle classes that Car Keys will work with. Add more if you wish!
---------------------------------------------------------------------------]]
CarKeysVehicles = {
	-- Half Life 2
	"prop_vehicle_jeep",
	"prop_vehicle_jeep_old",
	"prop_vehicle_airboat",
	"prop_vehicle_prisoner_pod",
	-- Simfphys
	"gmod_sent_vehicle_fphysics_base", -- Wheel class isn't included as we don't want people owning the wheels of a vehicle and not the rest of it :/
	-- SCars
	"sent_sakarias_car_banshee",
	"sent_sakarias_car_belair",
	"sent_sakarias_car_bobcat",
	"sent_sakarias_car_bus",
	"sent_sakarias_car_cadillac",
	"sent_sakarias_car_camaro",
	"sent_sakarias_car_chaos126p",
	"sent_sakarias_car_chevy66",
	"sent_sakarias_car_clydesdale",
	"sent_sakarias_car_comet",
	"sent_sakarias_car_delorean",
	"sent_sakarias_car_fordgt",
	"sent_sakarias_car_hedgehog",
	"sent_sakarias_car_hummer",
	"sent_sakarias_car_humvee",
	"sent_sakarias_car_huntley",
	"sent_sakarias_car_impala88",
	"sent_sakarias_car_junker4",
	"sent_sakarias_car_mothtruck",
	"sent_sakarias_car_mustang",
	"sent_sakarias_car_police",
	"sent_sakarias_car_ratmobile",
	"sent_sakarias_car_sabre",
	"sent_sakarias_car_stagpickup",
	"sent_sakarias_car_studebaker",
	"sent_sakarias_car_taxi",
	"sent_sakarias_car_1996corvette",
	"sent_sakarias_car_abrams",
	"sent_sakarias_car_brera",
	"sent_sakarias_car_carreragt",
	"sent_sakarias_car_dodgeram",
	"sent_sakarias_car_ferrari360",
	"sent_sakarias_car_ferrarif50",
	"sent_sakarias_car_ferrarif430",
	"sent_sakarias_car_fordmustangtr",
	"sent_sakarias_car_ilcar",
	"sent_sakarias_car_jimmygibbsjr",
	"sent_sakarias_car_lambodiablo",
	"sent_sakarias_car_lambodicop",
	"sent_sakarias_car_lambomurci",
	"sent_sakarias_car_lambomurcicop",
	"sent_sakarias_car_nissanskyline",
	"sent_sakarias_car_paganizonda",
	"sent_sakarias_car_porsche911",
	"sent_sakarias_car_porsche911cop",
	"sent_sakarias_car_suprarz",
	"sent_sakarias_car_toyotagtone",
	"sent_sakarias_car_vipercc",
	"sent_sakarias_car_vipersrt10",
	"sent_sakarias_car_yamahayfz450",
	"sent_sakarias_car_junker3",
	"sent_sakarias_car_junker2",
	"sent_sakarias_car_junker1"
}